---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: php-apache
  labels:
     author: venkatesh 
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      name: php-apache
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: intelliqit/mynew
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service 
metadata:
  name: php-apache
  labels:
    author: venkat 
spec:
  ports:
    - port: 80
  selector:
    run: php-apache
...