apiVersion: apps/v1
kind: DeamonSet 
metadata:
  name: nginx-deployment
  labels:
    type: proxy 
    author: venkatesh
spec:
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: nginx-pod
          image: nginx 
          ports:
            - containerPort: 80
              hostPort: 8080
            