apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: venkat
    type: proxy
spec:
  containers:
    - name: nginx-pod
      image: nginx 
      ports:
        - containerPort: 80
          hostPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - venkatesh