apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tomee-deployment
  labels:
    author: venkat
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: tomee-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: tomee-pod
          image: tomee 
          ports:
            - containerPort: 80
              hostPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slave2
                    operator: In 
                    values:
                      - venkat