apiVersion: apps/v1
kind: Deployment 
metadata:
  name: jenkins-deployment
  labels:
    author: venkat 
    type: ci-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      type: jenkins 
  template:
    metadata:
      name: jenkins-pod 
      labels:
        type: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 9090
...