---
apiVersion: v1 
kind: Pod 
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    type: cms
    author: venkatesh
spec:
  containers:
    - name: ghost-pod
      image: ghost 
      ports:
        - containerPort: 2368
          hostPort: 2368
...