apiVersion: v1 
kind: Pod 
metadata:
  name: postgres-pod
  labels:
    type: database
    author: venkatesh
spec:
  containers:
    - name: mydb
      image: postgres 
      env:
        - name: POSTGRES_PASSWORD
          value: venkat 
        - name: POSTGRES_USER
          value: kairam 
        - name: POSTGRES_DB
          value: root 
...