apiVersion: v1 
kind: Pod 
metadata:
  name: jenkins-pod
  labels:
    type: ci-cd
    author: venkatesh
spec:
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
...