apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: httpd-rc
  labels:
    type: appserver
    author: venkatesh
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: httpd-pod
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
...