apiVersion: v1 
kind: ReplicationController 
metadata:
  name: httpd-rc 
  labels:
    author: venkatesh
    type: webserver
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels: 
        type: webserver
    spec:
      containers:
        - name: httpd-pod
          image: httpd 
          ports:
            - containerPort: 80 
              hostPort: 8080
...