apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: tomee-rs
  labels:
    type: appserver
    author: venkatesh
spec:
  replicas: 3
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomee-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: tomee-pod 
          image: tomee
          ports:
            - containerPort: 80
              hostPort: 8080