apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy 
    author: venkat 
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy 
    spec:
      containers:
        - name: nginx-pod
          image: nginx 
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"