apiVersion: v1 
kind: Service 
metadata:
  name: myservice
  labels:
    author: venkat
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: webserver
    author: venkatesh
    