apiVersion: v1 
kind: Service 
metadata:
  name: newservice
  labels:
    author: venkat
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    type: ci-cd
    author: venkat