apiVersion: v1
kind: Pod 
metadata:
  name: tolerations
  labels:
    author: venkat
    type: proxy
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 9090
  tolerations:
    - key: slave1
      operator: Equal
      value: kairam
      effect: NoSchedule
      