apiVersion: v1 
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: db
    author: venkatesh
spec:
  containers:
    - name: redis-pod
      image: intelliqit/redis7 
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {}
...